version: '3'
services:
  app:
    container_name: yeric-blog-app
    build: .
    ports:
      - '8585:8585'
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres
    networks:
      - fullstack
    
  fullstack-postgres:
    image: postgres:9.6
    container_name: yeric-blog-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - fullstack
volumes:
  api:
  database_postgres:                  

networks:
  fullstack:
    driver: bridge
