version: '3.7'
services:    
  database:
    container_name: database
    env_file: .env
    image: postgres:14.1-alpine3.15
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    image: yeric-blog-app:v0.0.1
    ports:
      - "7070:7070"
    depends_on:
      - database
    restart: always
    volumes:
      - data:/images
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: web
  #   image: yeric-blog-web:v0.0.1
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - app
  #   restart: always
volumes:
  data: