version: '3'
services:
  app:
    container_name: yeric-blog-api
    build: .
    ports:
      - '7070:7070'
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres
    networks:
      - fullstack
    
  fullstack-postgres:
    image: postgres:14.1-alpine3.15
    container_name: postgres14_1
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5433:5433'
    networks:
      - fullstack
volumes:
  api:
  database_postgres:                  

networks:
  fullstack:
    driver: bridge
