name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: cirey.anaid.2107
          POSTGRES_DB: yeric-blog
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code inte the Go module directory
      uses: actions/checkout@v2
      
    - name: Run migrations
      run: make migrateup

    - name: Test
      run: go test -v ./...
